name: Enviar Noticias Diarias
on:
  schedule:
    - cron: '0 9 * * *' # Se ejecuta a las 9 AM UTC
  workflow_dispatch: # Permite ejecutarlo manualmente para probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests feedparser

      - name: Ejecutar script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python noticias.py
